services:
  service:
    build: .
    ports:
      - "${HTTP_PORT}:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: [ "./app"]
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
